server:
  port: 8090
  servlet:
    context-path: /api
spring:
  datasource:
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      url: jdbc:p6spy:mysql://localhost:3306/museum_db?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    database: 1
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  mvc:
    pathmatch:
      #解决异常：swagger Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.NullPointerException
      #因为Springfox使用的路径匹配是基于AntPathMatcher的，而Spring Boot 2.6.X使用的是PathPatternMatcher
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
knife4j: #开启增强模式
  enable: true
minio:
  endpoint: http://127.0.0.1:9005
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: collection-pic
workflow:
  token: "history-workflow"

langchain4j:
  dashscope:
    api-key: sk-b6880b99b30a46d7832d5cc51fd0a9d4
    model:
      chat: qwen-plus-2025-09-11                    # 默认模型
      simple: qwen-max                  # 简单问题模型（规则类）
      complex: qwen-flash-2025-07-28          # 复杂问题模型（文化、推荐类）
      embedding: text-embedding-v1
  chroma:
    enabled: true          # 设为 true 启用 Chroma，false 使用内存存储
    host: localhost
    port: 8000
    collection-name: museum-collection

# 日志配置
logging:
  level:
    root: INFO                              # 根日志级别
    com.museum: DEBUG                       # 您的应用包日志级别设为DEBUG
    com.museum.service.impl.agent: DEBUG   # Agent服务的详细调试日志
    dev.langchain4j: INFO                   # LangChain4j框架日志
    org.springframework: INFO              # Spring框架日志
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"




