server:
  port: 8090
  servlet:
    context-path: /api
spring:
  datasource:
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      url: jdbc:p6spy:mysql://localhost:3306/museum_db?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
  mvc:
    pathmatch:
      #解决异常：swagger Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.NullPointerException
      #因为Springfox使用的路径匹配是基于AntPathMatcher的，而Spring Boot 2.6.X使用的是PathPatternMatcher
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
knife4j: #开启增强模式
  enable: true

deepseek:
  api-key: sk-d2cc2c56fe494ea1aebd8c6cbfee4b5a
  base-url: https://api.deepseek.com/v1
sili:
  apiKey: sk-okyfpenukgiwlprqbhsutlelbnfakyhxfvcqftoyfkbyidnb
  baseUrl: https://api.siliconflow.cn/v1/
tongyi:
  apiKey: sk-b4ca1a8b48734565907af761fb97c31d
  model: qwen-turbo

